backend:
  name: git-gateway
  branch: BRANCH_PLACEHOLDER
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - {
              label: Heading,
              name: heading,
              widget: string,
              pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
            }
          - {
              label: Partner rows,
              name: partnerRows,
              widget: list,
              summary: 'Expand to edit partners',
              fields:
                [
                  {
                    label: "Direction",
                    name: "direction",
                    widget: "select",
                    options: [
                      { label: "Left to right", value: "ltr" },
                      { label: "Right to left", value: "rtl" },
                    ]
                  },
                  {
                    label: Partners,
                    name: partners,
                    widget: list,
                    min: 1,
                    fields:
                      [
                        { label: Text, name: text, widget: text },
                        { label: URL, name: url, widget: string },
                        {
                          label: "Font style",
                          name: "fontClassName",
                          widget: "select",
                          options: [
                            { label: "Sans normal", value: "font-sans font-normal" },
                            { label: "Serif light", value: "font-serif font-light tracking-tighter" },
                            { label: "Serif light italic", value: "font-serif font-light tracking-tighter italic" },
                          ]
                        },
                      ],
                  },
                ],
            }
          - {
              label: Numbered list,
              name: numberedList,
              widget: list,
              allow_add: false,
              max: 3,
              min: 3,
              summary: '{{fields.heading}}',
              fields:
                [
                  {
                    label: Heading,
                    name: heading,
                    widget: text,
                    pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
                  },
                  {
                    label: Text,
                    name: text,
                    widget: text,
                    pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
                  },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: image, name: image, widget: image, choose_url: true },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Accordion heading,
              name: accordionHeading,
              widget: string,
              pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
            }
          - {
              label: Accordion items,
              name: accordionItems,
              widget: list,
              fields:
                [
                  { label: Heading, name: heading, widget: text },
                  { label: Body, name: body, widget: textarea },
                ],
            }
          - {
              label: Partners heading,
              name: partnersHeading,
              widget: string,
              pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
            }
          - {
              label: Partners subheading,
              name: partnersSubheading,
              widget: string,
              pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
            }
          - {
              label: Partners subheading link,
              name: partnersSubheadingLink,
              widget: object,
              fields:
                [
                  { label: Link, name: href, widget: string },
                  { label: Text, name: text, widget: string },
                ],
            }
          - {
              label: Partners cards,
              name: partnersCards,
              widget: list,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: description, name: description, widget: string },
                  {
                    label: "Bullet color",
                    name: "bulletColorClassName",
                    widget: "select",
                    options: [
                      { label: "Summer rain", value: "bg-summer-rain" },
                      { label: "Voltage", value: "bg-voltage" },
                      { label: "Electric lime", value: "bg-electric-lime" },
                    ]
                  },
                  {
                    label: Bullets,
                    name: bullets,
                    widget: list,
                  },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: image, name: image, widget: image, choose_url: true },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ]
            }
          - {
              label: Footer CTA heading,
              name: footerCTAHeading,
              widget: string,
              pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
            }
          - {
              label: Footer CTA subheading,
              name: footerCTASubheading,
              widget: string,
              pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
            }
          - {
              label: Footer CTA Link,
              name: footerCTALink,
              widget: object,
              fields:
                [
                  {
                    label: "URL",
                    name: "url",
                    widget: string
                  },
                  {
                    label: "Text",
                    name: "text",
                    widget: string
                  }
                ]
            }
          - {
              label: Footer contact heading,
              name: footerContactHeading,
              widget: string,
              pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
            }
          - {
              label: Footer contact name,
              name: footerContactName,
              widget: string,
              pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
            }
          - {
              label: Footer contact title,
              name: footerContactTitle,
              widget: string,
              pattern: ['^.{0,100}$', "Must be 100 or fewer characters"]
            }
          - {
              label: Footer contact email,
              name: footerContactEmail,
              widget: string
            }
      - file: "src/pages/privacy.md"
        label: "Privacy"
        name: "privacy"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/terms.md"
        label: "Terms"
        name: "terms"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Body, name: body, widget: markdown }
  - name: "settings"
    label: "Settings"
    files:
      - file: "src/data/settings.yml"
        label: "Settings"
        name: "settings"
        fields:
          - label: Header
            name: header
            widget: object
            fields:
              [
                {
                  label: Logo,
                  name: logo,
                  widget: object,
                  fields:
                    [
                      { label: image, name: image, widget: image, choose_url: true },
                      { label: Alt, name: alt, widget: string },
                    ],
                },
              ]
          - label: Footer
            name: footer
            widget: object
            fields:
              [
                {
                  label: "Signoff",
                  name: "signoff",
                  widget: "string"
                },
                {
                  label: "Locations",
                  label_singular: "Location",
                  name: "locations",
                  widget: "list",
                  fields: [
                    { label: "Name", name: "name", widget: string }
                  ]
                },
                {
                  label: "Social media links",
                  label_singular: "Social media link",
                  name: "socialMediaLinks",
                  widget: "list",
                  fields: [
                    {
                      label: "Text",
                      name: "text",
                      widget: string
                    },
                    {
                      label: "URL",
                      name: "url",
                      widget: string
                    }
                  ]
                }
              ]
